export const travelLog = [
  {
    id: 'greece-sailing-trip',
    title: 'Greece sailing trip',
    timeframe: 'Ionian sailing + London night',
    color: '#4f97d6',
    provisional: false,
    summary: 'Boat nights in the Ionian, then one final hotel night in London.',
    stops: [
      {
        id: 'lefkada-start',
        name: 'Lefkada',
        coordinates: [20.71136, 38.82891],
        note: 'Lefkas Marina start.',
      },
      {
        id: 'vathy',
        name: 'Vathy',
        coordinates: [20.71864, 38.3643],
        note: 'Ithaca harbor.',
      },
      {
        id: 'kioni',
        name: 'Kioni',
        coordinates: [20.68924, 38.4502],
        note: 'Kioni harbor.',
      },
      {
        id: 'filiatro',
        name: 'Filiatro',
        coordinates: [20.6995, 38.4395],
        note: 'Approximate anchorage near the entrance of the Gulf of Kioni.',
      },
      {
        id: 'fiskardo-1',
        name: 'Fiskardo',
        coordinates: [20.581, 38.4565],
        note: 'First night in Fiskardo.',
      },
      {
        id: 'fiskardo-2',
        name: 'Fiskardo',
        coordinates: [20.581, 38.4565],
        note: 'Second night in Fiskardo.',
      },
      {
        id: 'lefkada-finish',
        name: 'Lefkada',
        coordinates: [20.71136, 38.82891],
        note: 'Back to Lefkas Marina.',
      },
      {
        id: 'london',
        name: 'London',
        coordinates: [-0.1276, 51.5072],
        note: 'One hotel night after the sailing trip.',
      },
    ],
  },
  {
    id: 'inca-trail-trip',
    title: 'Inca Trail + Cusco',
    timeframe: 'Peru hike + extra Cusco night',
    color: '#c37b2b',
    provisional: false,
    summary: 'Cusco, Sacred Valley, the Inca Trail to Machu Picchu, then one extra night back in Cusco.',
    stops: [
      {
        id: 'cusco-arrival',
        name: 'Cusco',
        coordinates: [-71.9675, -13.5319],
        note: 'Arrival and acclimation in Cusco.',
      },
      {
        id: 'chinchero',
        name: 'Chinchero',
        coordinates: [-72.0147, -13.3928],
        note: 'Sacred Valley cultural stop near Chinchero.',
      },
      {
        id: 'ollantaytambo-pretrail',
        name: 'Ollantaytambo',
        coordinates: [-72.2642, -13.2581],
        note: 'Last town stop before the trailhead.',
      },
      {
        id: 'km-82',
        name: 'Km 82 / Piscacucho',
        coordinates: [-72.545, -13.2817],
        note: 'Start of the classic Inca Trail hike.',
      },
      {
        id: 'wayllabamba',
        name: 'Wayllabamba',
        coordinates: [-72.4466, -13.2652],
        note: 'First trail campsite.',
      },
      {
        id: 'dead-womans-pass',
        name: 'Dead Woman’s Pass',
        coordinates: [-72.4862, -13.2052],
        note: 'Highest point on the hike.',
      },
      {
        id: 'runkurakay',
        name: 'Runkurakay',
        coordinates: [-72.50139, -13.22833],
        note: 'Inca site on the trail.',
      },
      {
        id: 'phuyupatamarca',
        name: 'Phuyupatamarca',
        coordinates: [-72.5337, -13.2027],
        note: 'Cloud-forest ruins with big mountain views.',
      },
      {
        id: 'intipata',
        name: 'Intipata',
        coordinates: [-72.5448, -13.1636],
        note: 'Terraces on the final approach.',
      },
      {
        id: 'winay-wayna',
        name: 'Wiñay Wayna',
        coordinates: [-72.5458, -13.1623],
        note: 'Final campsite / ruins before Sun Gate.',
      },
      {
        id: 'sun-gate',
        name: 'Sun Gate',
        coordinates: [-72.5449, -13.1631],
        note: 'First dramatic look at Machu Picchu.',
      },
      {
        id: 'machu-picchu',
        name: 'Machu Picchu',
        coordinates: [-72.545, -13.1631],
        note: 'Special marker for the big finish.',
        special: 'landmark',
      },
      {
        id: 'aguas-calientes',
        name: 'Aguas Calientes',
        coordinates: [-72.5252, -13.1547],
        note: 'Lunch and train out after the hike.',
      },
      {
        id: 'ollantaytambo-return',
        name: 'Ollantaytambo',
        coordinates: [-72.2642, -13.2581],
        note: 'Return by train into the Sacred Valley.',
      },
      {
        id: 'cusco-final-night',
        name: 'Cusco',
        coordinates: [-71.9675, -13.5319],
        note: 'Extra night in Cusco at the end.',
      },
    ],
  },
]
